[package]
name = "navmut-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
csv.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
